# ===============================
# Configuracion del Servidor
# ===============================
server.port=8080

# ===============================
# Configuracion de Base de Datos H2
# ===============================
spring.datasource.url=jdbc:h2:mem:kanbandb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===============================
# Configuracion de JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# 'update' actualiza la base de datos automaticamente segun las entidades que crees
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Habilitar la Consola Web de H2
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console